'use client';

import { type DiscountResult } from '@/lib/billing-utils';
import { type PatientRecord, type BillingItem } from '@/lib/db';

interface SOAProps {
  patient: PatientRecord;
  items: BillingItem[];
  summary: DiscountResult;
  billingNumber?: string;
  isPaid?: boolean;
}

export default function StatementOfAccount({ patient, items, summary, billingNumber, isPaid }: SOAProps) {
  return (
    <div className="bg-white p-8 rounded-xl shadow-2xl border-2 border-blue-900 space-y-6 max-w-2xl mx-auto print:shadow-none print:border-gray-300 print:max-w-full">
      {/* Header */}
      <div className="flex justify-between items-start border-b-2 border-blue-900 pb-4">
        <div>
          <h2 className="font-black text-2xl text-blue-900">STATEMENT OF ACCOUNT</h2>
          <p className="text-xs text-gray-500 uppercase tracking-widest font-bold">Philippine Hospital Information System</p>
        </div>
        <div className="text-right">
          <span className={`px-3 py-1 rounded text-xs font-black uppercase ${isPaid ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
            {isPaid ? 'PAID' : 'UNPAID'}
          </span>
          {billingNumber && <p className="text-[10px] font-bold text-gray-400 mt-2">SOA NO: {billingNumber}</p>}
        </div>
      </div>

      {/* Patient Info */}
      <div className="grid grid-cols-2 gap-4 text-sm border-b pb-4">
        <div>
          <p className="text-[10px] font-bold text-gray-400 uppercase">Patient Name</p>
          <p className="font-bold text-blue-900 uppercase">{patient.lastName}, {patient.firstName} {patient.middleName || ''}</p>
        </div>
        <div className="text-right">
          <p className="text-[10px] font-bold text-gray-400 uppercase">PhilHealth PIN</p>
          <p className="font-bold">{patient.memberPIN || 'N/A'}</p>
        </div>
      </div>

      {/* Itemized Charges */}
      <div className="space-y-2">
        <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Itemized Charges</p>
        <table className="w-full text-sm">
          <thead className="border-b text-[10px] uppercase font-bold text-gray-400">
            <tr>
              <th className="py-2 text-left">Description</th>
              <th className="py-2 text-right">Qty</th>
              <th className="py-2 text-right">Amount</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {items.map((item, idx) => (
              <tr key={idx}>
                <td className="py-2">{item.serviceName}</td>
                <td className="py-2 text-right">{item.quantity}</td>
                <td className="py-2 text-right">₱{item.subtotal.toFixed(2)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Summary */}
      <div className="space-y-3 pt-4 border-t-2 border-dashed border-gray-200">
        <div className="flex justify-between text-gray-600 font-bold">
          <span>Gross Charges:</span>
          <span>₱{summary.grossAmount.toFixed(2)}</span>
        </div>
        
        <div className="space-y-1 pl-4 text-sm">
          <div className="flex justify-between text-blue-700 italic">
            <span>Less: PhilHealth Benefit</span>
            <span>-₱{summary.philhealthBenefit.toFixed(2)}</span>
          </div>
          {summary.hmoCoverage > 0 && (
            <div className="flex justify-between text-purple-700 italic">
              <span>Less: HMO Coverage</span>
              <span>-₱{summary.hmoCoverage.toFixed(2)}</span>
            </div>
          )}
          {summary.vatExemption > 0 && (
            <div className="flex justify-between text-green-700 italic">
              <span>Less: VAT Exemption (12%)</span>
              <span>-₱{summary.vatExemption.toFixed(2)}</span>
            </div>
          )}
          {summary.seniorDiscount > 0 && (
            <div className="flex justify-between text-green-700 italic">
              <span>Less: Senior/PWD Discount (20%)</span>
              <span>-₱{summary.seniorDiscount.toFixed(2)}</span>
            </div>
          )}
        </div>

        <div className="flex justify-between text-2xl font-black pt-4 text-blue-900 border-t-2 border-blue-900">
          <span>NET DUE:</span>
          <span className="underline decoration-double">₱{summary.netAmount.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
        </div>
      </div>

      {/* Footer */}
      <div className="text-[8px] text-gray-400 italic text-center pt-8">
        <p>This is an official Statement of Account generated by the Philippine HIS Prototype.</p>
        <p>Generated on {new Date().toLocaleString()}</p>
      </div>
    </div>
  );
}
